# Generated by Django 5.1.7 on 2025-04-01 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=2)),
                ('diagnosis', models.CharField(max_length=25)),
                ('disease_stage', models.CharField(max_length=5)),
                ('enrollment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('annotation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=25)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.image')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scan_type', models.CharField(max_length=25)),
                ('scan_date', models.DateField()),
                ('scan_location', models.CharField(max_length=25)),
                ('storage_path', models.CharField(max_length=90)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='scan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.scan'),
        ),
    ]
