# Generated by Django 5.1.7 on 2025-04-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease_stage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
