# Generated by Django 5.1.7 on 2025-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_patient_disease_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
