# Generated by Django 5.1.7 on 2025-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_annotation_annotation_id_alter_image_image_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='image',
            name='storage_path',
            field=models.CharField(default='', max_length=90),
        ),
    ]
