# Generated by Django 5.1.7 on 2025-04-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_delete_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
