# Generated by Django 5.1.7 on 2025-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_image_storage_path_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(default='PNG', max_length=25),
        ),
    ]
