# Generated by Django 5.1.7 on 2025-04-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_image_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease_stage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
