# Generated by Django 5.1.7 on 2025-04-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_patient_disease_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
